#! /bin/bash

echo "-----------mrTanTA Installer----------"
echo "Enter custom name for installion:"
read NAME

#Create necessary directories
mkdir /etc/$NAME/

#Download necessary scripts and files
echo "Starting downloads"
wget -P /etc/$NAME/ https://raw.githubusercontent.com/Psiphon-Labs/psiphon-tunnel-core-binaries/master/linux/psiphon-tunnel-core-x86_64 --quiet
wget -P /etc/$NAME/ https://raw.githubusercontent.com/mrTanTA/PsiphonIRooni/main/psiphon.config --quiet
wget -O /usr/bin/$NAME https://raw.githubusercontent.com/mrTanTA/PsiphonIRooni/main/psiphonirooni --quiet
wget https://raw.githubusercontent.com/mrTanTA/PsiphonIRooni/refs/heads/main/pluninstaller --quiet
echo "Downloads finished"

echo " "
echo "Installing"

#Give these files the executable permission
chmod +x /etc/$NAME/psiphon-tunnel-core-x86_64
chmod +x /usr/bin/$NAME
echo "Installation finished"

echo " "
echo "Running post install checks"
echo " "
echo "Checking if files exist (Phase 1/2)"
if test -f /etc/$NAME/psiphon-tunnel-core-x86_64; then
  echo "Psiphon binary found."
else
  echo "Psiphon binary not found!"
fi

echo "Checking if launcher exists (Phase 2/2)"
if test -f /usr/bin/$NAME; then
  echo "Launcher found."
else
  echo "Launcher not found!"
fi

echo "All done! To run your service, just type: $NAME"
sleep 3
rm -rf plinstaller2
