#! /bin/bash

#To use the Uninstallation script, run sudo sh pluninstall

rm -rf /etc/psiphonirooni
rm -rf /usr/bin/psiphonirooni
rm -rf plinstaller2
rm -rf ca.psiphon.PsiphonTunnel.tunnel-core
rm -rf pluninstaller
